# fly.toml app configuration file generated for samuelki-datingapp on 2023-08-17T21:44:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "samuelki-datingapp"
primary_region = "sea"

[build]
  image = "samuelki62/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="djifk7kmx"
  CloudinarySettings__ApiKey="992178529918772"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
